// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0--rc1
// source: mapper_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateFieldName string `protobuf:"bytes,1,opt,name=TemplateFieldName,proto3" json:"TemplateFieldName,omitempty"`
	CustomerFieldName string `protobuf:"bytes,2,opt,name=CustomerFieldName,proto3" json:"CustomerFieldName,omitempty"`
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapping.ProtoReflect.Descriptor instead.
func (*Mapping) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{0}
}

func (x *Mapping) GetTemplateFieldName() string {
	if x != nil {
		return x.TemplateFieldName
	}
	return ""
}

func (x *Mapping) GetCustomerFieldName() string {
	if x != nil {
		return x.CustomerFieldName
	}
	return ""
}

type MapDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint32     `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreatedAt      string     `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      string     `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt      string     `protobuf:"bytes,4,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	MapName        string     `protobuf:"bytes,5,opt,name=MapName,proto3" json:"MapName,omitempty"`
	MapDescription string     `protobuf:"bytes,6,opt,name=MapDescription,proto3" json:"MapDescription,omitempty"`
	CategoryName   string     `protobuf:"bytes,7,opt,name=CategoryName,proto3" json:"CategoryName,omitempty"`
	MapStatus      bool       `protobuf:"varint,8,opt,name=MapStatus,proto3" json:"MapStatus,omitempty"`
	CreatedBy      string     `protobuf:"bytes,9,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedBy      string     `protobuf:"bytes,10,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	Mappings       []*Mapping `protobuf:"bytes,11,rep,name=Mappings,proto3" json:"Mappings,omitempty"`
}

func (x *MapDetails) Reset() {
	*x = MapDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDetails) ProtoMessage() {}

func (x *MapDetails) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDetails.ProtoReflect.Descriptor instead.
func (*MapDetails) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{1}
}

func (x *MapDetails) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MapDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MapDetails) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *MapDetails) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *MapDetails) GetMapDescription() string {
	if x != nil {
		return x.MapDescription
	}
	return ""
}

func (x *MapDetails) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *MapDetails) GetMapStatus() bool {
	if x != nil {
		return x.MapStatus
	}
	return false
}

func (x *MapDetails) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *MapDetails) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *MapDetails) GetMappings() []*Mapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type MapStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapStatus bool `protobuf:"varint,1,opt,name=MapStatus,proto3" json:"MapStatus,omitempty"`
}

func (x *MapStatus) Reset() {
	*x = MapStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapStatus) ProtoMessage() {}

func (x *MapStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapStatus.ProtoReflect.Descriptor instead.
func (*MapStatus) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{2}
}

func (x *MapStatus) GetMapStatus() bool {
	if x != nil {
		return x.MapStatus
	}
	return false
}

type VinTemplateFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VinTemplateFields []string `protobuf:"bytes,1,rep,name=VinTemplateFields,proto3" json:"VinTemplateFields,omitempty"`
}

func (x *VinTemplateFields) Reset() {
	*x = VinTemplateFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VinTemplateFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VinTemplateFields) ProtoMessage() {}

func (x *VinTemplateFields) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VinTemplateFields.ProtoReflect.Descriptor instead.
func (*VinTemplateFields) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{3}
}

func (x *VinTemplateFields) GetVinTemplateFields() []string {
	if x != nil {
		return x.VinTemplateFields
	}
	return nil
}

type CustomerTemplateFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerTemplateFields []string `protobuf:"bytes,1,rep,name=CustomerTemplateFields,proto3" json:"CustomerTemplateFields,omitempty"`
}

func (x *CustomerTemplateFields) Reset() {
	*x = CustomerTemplateFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerTemplateFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerTemplateFields) ProtoMessage() {}

func (x *CustomerTemplateFields) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerTemplateFields.ProtoReflect.Descriptor instead.
func (*CustomerTemplateFields) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerTemplateFields) GetCustomerTemplateFields() []string {
	if x != nil {
		return x.CustomerTemplateFields
	}
	return nil
}

type CreateMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId     uint32 `protobuf:"varint,1,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`
	MapName        string `protobuf:"bytes,2,opt,name=MapName,proto3" json:"MapName,omitempty"`
	MapDescription string `protobuf:"bytes,3,opt,name=MapDescription,proto3" json:"MapDescription,omitempty"`
	CategoryName   string `protobuf:"bytes,4,opt,name=CategoryName,proto3" json:"CategoryName,omitempty"`
}

func (x *CreateMapRequest) Reset() {
	*x = CreateMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMapRequest) ProtoMessage() {}

func (x *CreateMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMapRequest.ProtoReflect.Descriptor instead.
func (*CreateMapRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMapRequest) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *CreateMapRequest) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *CreateMapRequest) GetMapDescription() string {
	if x != nil {
		return x.MapDescription
	}
	return ""
}

func (x *CreateMapRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type CreateMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32       `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MapDetails `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CreateMapResponse) Reset() {
	*x = CreateMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMapResponse) ProtoMessage() {}

func (x *CreateMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMapResponse.ProtoReflect.Descriptor instead.
func (*CreateMapResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMapResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMapResponse) GetData() *MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMapDetailsByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetMapDetailsByIDRequest) Reset() {
	*x = GetMapDetailsByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapDetailsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDetailsByIDRequest) ProtoMessage() {}

func (x *GetMapDetailsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDetailsByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMapDetailsByIDRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetMapDetailsByIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMapDetailsByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32       `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MapDetails `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetMapDetailsByIdResponse) Reset() {
	*x = GetMapDetailsByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapDetailsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDetailsByIdResponse) ProtoMessage() {}

func (x *GetMapDetailsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDetailsByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMapDetailsByIdResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetMapDetailsByIdResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMapDetailsByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMapDetailsByIdResponse) GetData() *MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMapDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32         `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    []*MapDetails `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetMapDetailsResponse) Reset() {
	*x = GetMapDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDetailsResponse) ProtoMessage() {}

func (x *GetMapDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetMapDetailsResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetMapDetailsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMapDetailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMapDetailsResponse) GetData() []*MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateMapDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	MapName        string `protobuf:"bytes,2,opt,name=MapName,proto3" json:"MapName,omitempty"`
	MapDescription string `protobuf:"bytes,3,opt,name=MapDescription,proto3" json:"MapDescription,omitempty"`
	CategoryName   string `protobuf:"bytes,4,opt,name=CategoryName,proto3" json:"CategoryName,omitempty"`
}

func (x *UpdateMapDetailsRequest) Reset() {
	*x = UpdateMapDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMapDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMapDetailsRequest) ProtoMessage() {}

func (x *UpdateMapDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMapDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMapDetailsRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMapDetailsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMapDetailsRequest) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *UpdateMapDetailsRequest) GetMapDescription() string {
	if x != nil {
		return x.MapDescription
	}
	return ""
}

func (x *UpdateMapDetailsRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type UpdateMapDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32       `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MapDetails `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UpdateMapDetailsResponse) Reset() {
	*x = UpdateMapDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMapDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMapDetailsResponse) ProtoMessage() {}

func (x *UpdateMapDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMapDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMapDetailsResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMapDetailsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateMapDetailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMapDetailsResponse) GetData() *MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type EnableDisableMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *EnableDisableMapRequest) Reset() {
	*x = EnableDisableMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableDisableMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableDisableMapRequest) ProtoMessage() {}

func (x *EnableDisableMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableDisableMapRequest.ProtoReflect.Descriptor instead.
func (*EnableDisableMapRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{12}
}

func (x *EnableDisableMapRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EnableDisableMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32       `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MapDetails `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *EnableDisableMapResponse) Reset() {
	*x = EnableDisableMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableDisableMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableDisableMapResponse) ProtoMessage() {}

func (x *EnableDisableMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableDisableMapResponse.ProtoReflect.Descriptor instead.
func (*EnableDisableMapResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{13}
}

func (x *EnableDisableMapResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EnableDisableMapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnableDisableMapResponse) GetData() *MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPreFilledMappingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VinTemplateFields      []string `protobuf:"bytes,1,rep,name=VinTemplateFields,proto3" json:"VinTemplateFields,omitempty"`
	CustomerTemplateFields []string `protobuf:"bytes,2,rep,name=CustomerTemplateFields,proto3" json:"CustomerTemplateFields,omitempty"`
}

func (x *GetPreFilledMappingsRequest) Reset() {
	*x = GetPreFilledMappingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreFilledMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreFilledMappingsRequest) ProtoMessage() {}

func (x *GetPreFilledMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreFilledMappingsRequest.ProtoReflect.Descriptor instead.
func (*GetPreFilledMappingsRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetPreFilledMappingsRequest) GetVinTemplateFields() []string {
	if x != nil {
		return x.VinTemplateFields
	}
	return nil
}

func (x *GetPreFilledMappingsRequest) GetCustomerTemplateFields() []string {
	if x != nil {
		return x.CustomerTemplateFields
	}
	return nil
}

type GetPreFilledMappingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32      `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    []*Mapping `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetPreFilledMappingsResponse) Reset() {
	*x = GetPreFilledMappingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreFilledMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreFilledMappingsResponse) ProtoMessage() {}

func (x *GetPreFilledMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreFilledMappingsResponse.ProtoReflect.Descriptor instead.
func (*GetPreFilledMappingsResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetPreFilledMappingsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPreFilledMappingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPreFilledMappingsResponse) GetData() []*Mapping {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetVinTemplateHeadersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateID uint32 `protobuf:"varint,1,opt,name=TemplateID,proto3" json:"TemplateID,omitempty"`
}

func (x *GetVinTemplateHeadersRequest) Reset() {
	*x = GetVinTemplateHeadersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVinTemplateHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVinTemplateHeadersRequest) ProtoMessage() {}

func (x *GetVinTemplateHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVinTemplateHeadersRequest.ProtoReflect.Descriptor instead.
func (*GetVinTemplateHeadersRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetVinTemplateHeadersRequest) GetTemplateID() uint32 {
	if x != nil {
		return x.TemplateID
	}
	return 0
}

type GetVinTemplateHeadersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32              `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string             `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *VinTemplateFields `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetVinTemplateHeadersResponse) Reset() {
	*x = GetVinTemplateHeadersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVinTemplateHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVinTemplateHeadersResponse) ProtoMessage() {}

func (x *GetVinTemplateHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVinTemplateHeadersResponse.ProtoReflect.Descriptor instead.
func (*GetVinTemplateHeadersResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetVinTemplateHeadersResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetVinTemplateHeadersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVinTemplateHeadersResponse) GetData() *VinTemplateFields {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCustomerTemplateHeadersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *GetCustomerTemplateHeadersRequest) Reset() {
	*x = GetCustomerTemplateHeadersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerTemplateHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerTemplateHeadersRequest) ProtoMessage() {}

func (x *GetCustomerTemplateHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerTemplateHeadersRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerTemplateHeadersRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetCustomerTemplateHeadersRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type GetCustomerTemplateHeadersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *CustomerTemplateFields `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetCustomerTemplateHeadersResponse) Reset() {
	*x = GetCustomerTemplateHeadersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerTemplateHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerTemplateHeadersResponse) ProtoMessage() {}

func (x *GetCustomerTemplateHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerTemplateHeadersResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerTemplateHeadersResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetCustomerTemplateHeadersResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCustomerTemplateHeadersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCustomerTemplateHeadersResponse) GetData() *CustomerTemplateFields {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddMappingsToMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId    uint32     `protobuf:"varint,1,opt,name=MapId,proto3" json:"MapId,omitempty"`
	Mappings []*Mapping `protobuf:"bytes,2,rep,name=Mappings,proto3" json:"Mappings,omitempty"`
}

func (x *AddMappingsToMapRequest) Reset() {
	*x = AddMappingsToMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMappingsToMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMappingsToMapRequest) ProtoMessage() {}

func (x *AddMappingsToMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMappingsToMapRequest.ProtoReflect.Descriptor instead.
func (*AddMappingsToMapRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{20}
}

func (x *AddMappingsToMapRequest) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *AddMappingsToMapRequest) GetMappings() []*Mapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type AddMappingsToMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32       `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MapDetails `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *AddMappingsToMapResponse) Reset() {
	*x = AddMappingsToMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMappingsToMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMappingsToMapResponse) ProtoMessage() {}

func (x *AddMappingsToMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMappingsToMapResponse.ProtoReflect.Descriptor instead.
func (*AddMappingsToMapResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{21}
}

func (x *AddMappingsToMapResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddMappingsToMapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddMappingsToMapResponse) GetData() *MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type RemoveMappingFromMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32   `protobuf:"varint,1,opt,name=MapId,proto3" json:"MapId,omitempty"`
	Mapping *Mapping `protobuf:"bytes,2,opt,name=Mapping,proto3" json:"Mapping,omitempty"`
}

func (x *RemoveMappingFromMapRequest) Reset() {
	*x = RemoveMappingFromMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMappingFromMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMappingFromMapRequest) ProtoMessage() {}

func (x *RemoveMappingFromMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMappingFromMapRequest.ProtoReflect.Descriptor instead.
func (*RemoveMappingFromMapRequest) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveMappingFromMapRequest) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *RemoveMappingFromMapRequest) GetMapping() *Mapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

type RemoveMappingFromMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32       `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MapDetails `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RemoveMappingFromMapResponse) Reset() {
	*x = RemoveMappingFromMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMappingFromMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMappingFromMapResponse) ProtoMessage() {}

func (x *RemoveMappingFromMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMappingFromMapResponse.ProtoReflect.Descriptor instead.
func (*RemoveMappingFromMapResponse) Descriptor() ([]byte, []int) {
	return file_mapper_service_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveMappingFromMapResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemoveMappingFromMapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveMappingFromMapResponse) GetData() *MapDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mapper_service_proto protoreflect.FileDescriptor

var file_mapper_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x2c,
	0x0a, 0x11, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xdc, 0x02, 0x0a, 0x0a, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x4d, 0x61,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x42, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x12, 0x24, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x29, 0x0a, 0x09, 0x4d, 0x61, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x4d, 0x61, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x41, 0x0a, 0x11, 0x56, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x56, 0x69, 0x6e,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x56, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x50, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x12, 0x36, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x61, 0x70, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x22, 0x6e, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x8f, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x61,
	0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6d, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x17, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x6d, 0x0a, 0x18, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x83, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x11, 0x56, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x56, 0x69, 0x6e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x36, 0x0a,
	0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x16, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x6e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x46,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x56, 0x69, 0x6e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x44, 0x22, 0x79, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x56, 0x69, 0x6e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x56, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x37, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x22, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x55, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x54, 0x6f,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x6d, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x57, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x07, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x71,
	0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46,
	0x72, 0x6f, 0x6d, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x32, 0x95, 0x06, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x44, 0x42, 0x4d, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x70, 0x12, 0x11, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x19, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x10, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4d,
	0x61, 0x70, 0x12, 0x18, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x1c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x56, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x6e, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x6e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x22, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x41,
	0x64, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x4d, 0x61, 0x70, 0x12,
	0x18, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x4d,
	0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x41, 0x64, 0x64, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x61, 0x70, 0x12, 0x1c, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x6f, 0x6d,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapper_service_proto_rawDescOnce sync.Once
	file_mapper_service_proto_rawDescData = file_mapper_service_proto_rawDesc
)

func file_mapper_service_proto_rawDescGZIP() []byte {
	file_mapper_service_proto_rawDescOnce.Do(func() {
		file_mapper_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapper_service_proto_rawDescData)
	})
	return file_mapper_service_proto_rawDescData
}

var file_mapper_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_mapper_service_proto_goTypes = []interface{}{
	(*Mapping)(nil),                            // 0: Mapping
	(*MapDetails)(nil),                         // 1: MapDetails
	(*MapStatus)(nil),                          // 2: MapStatus
	(*VinTemplateFields)(nil),                  // 3: VinTemplateFields
	(*CustomerTemplateFields)(nil),             // 4: CustomerTemplateFields
	(*CreateMapRequest)(nil),                   // 5: CreateMapRequest
	(*CreateMapResponse)(nil),                  // 6: CreateMapResponse
	(*GetMapDetailsByIDRequest)(nil),           // 7: GetMapDetailsByIDRequest
	(*GetMapDetailsByIdResponse)(nil),          // 8: GetMapDetailsByIdResponse
	(*GetMapDetailsResponse)(nil),              // 9: GetMapDetailsResponse
	(*UpdateMapDetailsRequest)(nil),            // 10: UpdateMapDetailsRequest
	(*UpdateMapDetailsResponse)(nil),           // 11: UpdateMapDetailsResponse
	(*EnableDisableMapRequest)(nil),            // 12: EnableDisableMapRequest
	(*EnableDisableMapResponse)(nil),           // 13: EnableDisableMapResponse
	(*GetPreFilledMappingsRequest)(nil),        // 14: GetPreFilledMappingsRequest
	(*GetPreFilledMappingsResponse)(nil),       // 15: GetPreFilledMappingsResponse
	(*GetVinTemplateHeadersRequest)(nil),       // 16: GetVinTemplateHeadersRequest
	(*GetVinTemplateHeadersResponse)(nil),      // 17: GetVinTemplateHeadersResponse
	(*GetCustomerTemplateHeadersRequest)(nil),  // 18: GetCustomerTemplateHeadersRequest
	(*GetCustomerTemplateHeadersResponse)(nil), // 19: GetCustomerTemplateHeadersResponse
	(*AddMappingsToMapRequest)(nil),            // 20: AddMappingsToMapRequest
	(*AddMappingsToMapResponse)(nil),           // 21: AddMappingsToMapResponse
	(*RemoveMappingFromMapRequest)(nil),        // 22: RemoveMappingFromMapRequest
	(*RemoveMappingFromMapResponse)(nil),       // 23: RemoveMappingFromMapResponse
	(*emptypb.Empty)(nil),                      // 24: google.protobuf.Empty
}
var file_mapper_service_proto_depIdxs = []int32{
	0,  // 0: MapDetails.Mappings:type_name -> Mapping
	1,  // 1: CreateMapResponse.Data:type_name -> MapDetails
	1,  // 2: GetMapDetailsByIdResponse.Data:type_name -> MapDetails
	1,  // 3: GetMapDetailsResponse.Data:type_name -> MapDetails
	1,  // 4: UpdateMapDetailsResponse.Data:type_name -> MapDetails
	1,  // 5: EnableDisableMapResponse.Data:type_name -> MapDetails
	0,  // 6: GetPreFilledMappingsResponse.Data:type_name -> Mapping
	3,  // 7: GetVinTemplateHeadersResponse.Data:type_name -> VinTemplateFields
	4,  // 8: GetCustomerTemplateHeadersResponse.Data:type_name -> CustomerTemplateFields
	0,  // 9: AddMappingsToMapRequest.Mappings:type_name -> Mapping
	1,  // 10: AddMappingsToMapResponse.Data:type_name -> MapDetails
	0,  // 11: RemoveMappingFromMapRequest.Mapping:type_name -> Mapping
	1,  // 12: RemoveMappingFromMapResponse.Data:type_name -> MapDetails
	5,  // 13: FileToDBMapper.CreateMap:input_type -> CreateMapRequest
	7,  // 14: FileToDBMapper.GetMapDetailsByID:input_type -> GetMapDetailsByIDRequest
	24, // 15: FileToDBMapper.GetMapDetails:input_type -> google.protobuf.Empty
	10, // 16: FileToDBMapper.UpdateMapDetails:input_type -> UpdateMapDetailsRequest
	12, // 17: FileToDBMapper.EnableDisableMap:input_type -> EnableDisableMapRequest
	14, // 18: FileToDBMapper.GetPreFilledMappings:input_type -> GetPreFilledMappingsRequest
	16, // 19: FileToDBMapper.GetVinTemplateHeaders:input_type -> GetVinTemplateHeadersRequest
	18, // 20: FileToDBMapper.GetCustomerTemplateHeaders:input_type -> GetCustomerTemplateHeadersRequest
	20, // 21: FileToDBMapper.AddMappingsToMap:input_type -> AddMappingsToMapRequest
	22, // 22: FileToDBMapper.RemoveMappingFromMap:input_type -> RemoveMappingFromMapRequest
	6,  // 23: FileToDBMapper.CreateMap:output_type -> CreateMapResponse
	8,  // 24: FileToDBMapper.GetMapDetailsByID:output_type -> GetMapDetailsByIdResponse
	9,  // 25: FileToDBMapper.GetMapDetails:output_type -> GetMapDetailsResponse
	11, // 26: FileToDBMapper.UpdateMapDetails:output_type -> UpdateMapDetailsResponse
	13, // 27: FileToDBMapper.EnableDisableMap:output_type -> EnableDisableMapResponse
	15, // 28: FileToDBMapper.GetPreFilledMappings:output_type -> GetPreFilledMappingsResponse
	17, // 29: FileToDBMapper.GetVinTemplateHeaders:output_type -> GetVinTemplateHeadersResponse
	19, // 30: FileToDBMapper.GetCustomerTemplateHeaders:output_type -> GetCustomerTemplateHeadersResponse
	21, // 31: FileToDBMapper.AddMappingsToMap:output_type -> AddMappingsToMapResponse
	23, // 32: FileToDBMapper.RemoveMappingFromMap:output_type -> RemoveMappingFromMapResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_mapper_service_proto_init() }
func file_mapper_service_proto_init() {
	if File_mapper_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapper_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VinTemplateFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerTemplateFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapDetailsByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapDetailsByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMapDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMapDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableDisableMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableDisableMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreFilledMappingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreFilledMappingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVinTemplateHeadersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVinTemplateHeadersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerTemplateHeadersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerTemplateHeadersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMappingsToMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMappingsToMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMappingFromMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMappingFromMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapper_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapper_service_proto_goTypes,
		DependencyIndexes: file_mapper_service_proto_depIdxs,
		MessageInfos:      file_mapper_service_proto_msgTypes,
	}.Build()
	File_mapper_service_proto = out.File
	file_mapper_service_proto_rawDesc = nil
	file_mapper_service_proto_goTypes = nil
	file_mapper_service_proto_depIdxs = nil
}
